### ISSUE TITLE
Using xlsx throws error File type is not supported for read

### ISSUE THREAD

**Issue by haschdl** [pyexcel/sphinxcontrib-excel#1]
Documentation says that xlsx is supportted, however Sphinx will rethrow the following exception:

```
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\pyexcel\plugins\__init__.py", line 118, in find_file_type_from_file_name
    constants.FILE_TYPE_NOT_SUPPORTED_FMT % (file_type, action)
pyexcel.exceptions.FileTypeNotSupported: File type 'xlsx"' is not supported for read.
```

Markup:
```
.. pyexcel-table:: "c:/temp/demo.xlsx"
```

**Comment by chfw** [comment]
Please check if pyexcel-xls is installed with sphinxcontrib-excel. That is the plugin to read xlsx and should have been installed as dependency.

**Comment by haschdl** [comment]
Hello, I ended up using `.. raw: hml`and adding an embed code from Excel online, therefore I will close the issue as I'm not able to investigate it further.
